### ISSUE TITLE
一键刷Q币成功了！！！谢谢大佬

### ISSUE THREAD

**Issue by JerrySukin** [WWILLV/GodOfHacker#15]
成功拿到了朝思暮想的火麒麟，别人看见都不敢打我了，哈哈
只是有个BUG，就是用了这个软件后网络有点卡，网银的余额一直刷不出来，望解决。

**Comment by iReQAQ** [comment]
真的吗？我也是刷新不出来，我玩英雄联盟，解决了请帮我说一下。
